### ISSUE TITLE
Windows 7: NavBar Vertical Scroll Bar is Flickering

### ISSUE THREAD

**Issue by Yaron10** [pnedev/comparePlus#304]
Hello Pavel,

**STR:**
Compare the [Find files](https://github.com/pnedev/compare-plugin/files/9066086/Find.zip).
Set focus to the NavBar by clicking on its title bar.

**Result:**
On Windows 7, the NavBar vertical scroll bar is flickering.

**NOTE:**
1. The issue does not exist on Windows 10.
2. It seems to be an old issue.

Thank you for looking into it.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Let's leave it as a known issue.
Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

👍 
Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

The flickering is gone by moving the focus to the editor.
Doing that is obviously better than the flickering.

Still - would you consider it a proper fix? Do you think the issue should be closed?
It's certainly not worth your time at this stage.

Thank you very much. 👍

**Comment by pnedev** [comment]
Hello Yaron,

I don't really care where the focus would be in that case. I just need to move it somewhere so the scrollbar does not receive it (so it does not flicker).
Where do you think is the appropriate position ? I can set the focus to the previous element that had it or I can simply let it be at the NavBar header but currently if I do so and the user then presses `Up`, `Down`, `PageUp` or `PageDown` keys then the scroller would move thumb position and start to flicker again. I haven't found a way yet to stop that.

Thank you and
BR

**Comment by Yaron10** [comment]
Hello Pavel,

What bothered me was the inability to set focus to the NavBar by clicking on its title bar.
(Although I can't think of a practical reason to enable it, other docking panels do get focus in that case).
But it's certainly better than the flickering.

Thanks again for your hard work.

BR

**Comment by Yaron10** [comment]
Hello again Pavel,

The Up, Down, PageUp or PageDown keys are the practical reason to enable the NavBar to get focus. :)

Thank you.

**Comment by pnedev** [comment]
Hello Yaron,

> The Up, Down, PageUp or PageDown keys are the practical reason to enable the NavBar to get focus

That's very true although I doubt someone would rely on focus+keyboard to move the scrollbar.

Thanks and
BR

**Comment by Yaron10** [comment]
Hello Pavel,

> although I doubt someone would rely on focus+keyboard to move the scrollbar.

As a "mouse-user", I certainly wouldn't.

I'm glad you've removed the "ComparePlus v1" milestone from this issue. :)

Thanks again.

**Comment by pnedev** [comment]
Hello Yaron,

You are right - we shouldn't waste time on "non-ComparePlus v1" issues :)

I couldn't find a good way to circumvent that and I think we are safe with the current implementation of not accepting the focus on the NavBar at all. So the scroller is accessible only via the mouse.
I will close this issue now and consider it fixed - no scroller flicker anymore.

Thank you

**Comment by Yaron10** [comment]
👍 
Thanks again Pavel.
