### ISSUE TITLE
Some "Last" Issues

### ISSUE THREAD

**Issue by Yaron10** [pnedev/comparePlus#305]
Hello Pavel,

Could you please compare [these files](https://github.com/pnedev/compare-plugin/files/9184520/Test.zip)?

Activate `TestNew.rc`.
Press `Last` (the result now depends on the window size).
Press `Last` again.

**Result:**
1. The line is invisible.
2. The caret is at the *end of the line*.

It might be what you meant in https://github.com/pnedev/compare-plugin/issues/246#issuecomment-1188950055. :)

Thank you. I appreciate it.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Thank you for the report :+1: 

Yes, it might be connected to what we talked about in #246 .
The navigation issues are the most complex by far due to the new alignment approach.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks again for your work and time. Much appreciated. 👍 

BR

**Comment by pnedev** [comment]
Hello Yaron,

That issue should be fixed with build https://ci.appveyor.com/project/pnedev/compareplus/builds/44533437.
Could you please verify it?

Thank You!

**Comment by Yaron10** [comment]
Hello my friend Pavel,

I hope you're doing well.

Thank you very much for the new commit. 👍 
I'm glad you've solved the navigation issues, and I truly appreciate your excellent hard work.

I've just noticed a minor issue related to "Last".
Place the caret at the end of `TestOld.rc`.
Scroll so that the beginning of line 26 is not visible.
![תמונה](https://user-images.githubusercontent.com/10229320/185814128-9bb39f59-2b5e-4af6-b3de-b3126512fd86.png)
Press "Last".

Shouldn't line 26 blink?

***

I'll be away for a few days.
I''l refer to the other issues when I get back (probably Thursday).

Thanks again and best regards.

**Comment by pnedev** [comment]
Hello my friend,

Thank you for the quick reply and for the feedback.
I'll check the minor issue you found :+1: 

I don't wont to delay the first release any longer so I will do it in 1 to 3 days.
Any new fixes will go to the next release.
Thank you once again for all the help hunting down bugs and for all the great suggestions, I truly appreciate that.

Take a good and pleasant rest (or best of luck if it is work related).
"See" you soon ;)

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> I don't wont to delay the first release any longer
Any new fixes will go to the next release.

👍 
I'm really glad this is your decision.
I suppose we'll exchange some more words before the first release, but I'll thank you now again for your brilliant and hard work along the past years. Highly appreciated.

I had a short vacation. Thank you for the kind wishes.

BR

**Comment by pnedev** [comment]
Hello Yaron,

I hope you were able to get some rest and enjoy your vacation.

I got delayed again so I hope we'll get the chance to discuss the last fixes before the release. I appreciate that.
It should be ready on 1st of September, latest.
Thank you.

BR

**Comment by pnedev** [comment]
Hello Yaron,

The minor issue should be fixed in this [build](https://ci.appveyor.com/project/pnedev/compareplus/builds/44616729).
Thanks.

BR

**Comment by pnedev** [comment]
Hello Yaron,

> I've come across another minor issue (for the next release).

It is fixed in this [build](https://ci.appveyor.com/project/pnedev/compareplus/builds/44621852).
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

What a maestro! Bravo! 👍 

Thank you very much for the quick fix.

BR
