### ISSUE TITLE
ARM64 build

### ISSUE THREAD

**Issue by davinderc** [pnedev/comparePlus#309]
Hi, I'm running Notepad++ on a Windows 11 VM on a Mac M1 and would like to use this plugin. However, it doesn't show up for me and it seems that's because it doesn't have an ARM build for it. Could you add an ARM build?

Thanks!

**Comment by pnedev** [comment]
Hi,

I will release the first version of ComparePlus plugin in a few days and it will have ARM64 build.
It will be compatible only with Notepad++ versions above 8.4.2 (included).

BR

**Comment by pnedev** [comment]
Hi again,

ComparePlus will be out on 1st of September latest.
I will close this thread now.
