### ISSUE TITLE
Regex ignores

### ISSUE THREAD

**Issue by Gitoffthelawn** [pnedev/comparePlus#310]
The readme file currently states:

> ...It is highly customizable, can ignore spaces, empty lines, letter cases, regexes, can find moves and show character diffs. Several compared file pairs can be active and displayed at the same time...

How does one ignore regexes?  I'm not seeing any place to specify a regex or documentation with that detail.

**Comment by pnedev** [comment]
Ignore regex is a feature of the ComparePlus plugin that is not officially released yet.
Its first release will be in a few days, I just need to finalize some things.

**Comment by Gitoffthelawn** [comment]
Thank you!
