### ISSUE TITLE
Readme vs. Releases

### ISSUE THREAD

**Issue by Gitoffthelawn** [pnedev/comparePlus#311]
The current readme file talks about `Compare-plugin` and `ComparePlus`.

The releases page (https://github.com/pnedev/comparePlus/releases) provides releases of `ComparePlugin.dll` v2.00+.  Are these considered to be `ComparePlus`?  Looking at appveyor, it looks like this is true.  If so, perhaps some editing of the readme is warranted to clear this up.  If you would like me to make the edits, just ask, and I'll get it done.

Thanks for the useful tool.

**Comment by pnedev** [comment]
Compare-plugin and  ComparePlus plugin are different plugins. Compare-plugin is the old one and ComparePlus is its successor but it is still not officially released.
Its first release will be in a few days, I just need to finalize some things.

Until ComparePlus is released things are indeed a bit messy, sorry for the misunderstanding.
You are welcome. :+1:

**Comment by Gitoffthelawn** [comment]
Thank you for the explanation! 👍🏾
