### ISSUE TITLE
Comparing against clipboard

### ISSUE THREAD

**Issue by Gitoffthelawn** [pnedev/comparePlus#312]
The readme file currently states:

> ...Diff a file or parts of it against clipboard text content...

How does one compare a file or parts of it against the clipboard?

**Comment by pnedev** [comment]
'Diff against clipboard' is a feature of the ComparePlus plugin that is not officially released yet.
Its first release will be in a few days, I just need to finalize some things.

**Comment by Gitoffthelawn** [comment]
Thanks again!
