### ISSUE TITLE
FR: Compare only specific columns

### ISSUE THREAD

**Issue by Gitoffthelawn** [pnedev/comparePlus#313]
It will be *very* useful for this tool to compare specific columns within 2 files.

For example, File 1:
```
12345 Alpha
23456 Beta
34567 Gamma
```
and File 2:
```
12345 Alpha
23456 Gamma
34567 Delta
```
If the user specifies to only compare columns 1-5, then no differences will be found with the above.

What will make this so powerful, is that unlike other tools, this tool will also show the context of any changes since you can see the entire content of both files within Notepad++.

**Comment by pnedev** [comment]
That is exactly the purpose of the Ignore regex option.
For your example you'll just need to specify the regex that will ignore all columns after the fifth one and then run compare.
 
Ignore regex is a feature of the ComparePlus plugin that is not officially released yet.
Its first release will be in a few days, I just need to finalize some things.

You'll find the Ignore regex option in the plugins menu along all other Ignore options.

**Comment by Gitoffthelawn** [comment]
This is going to be very powerful.  I look forward to it.  Thank you!
