### ISSUE TITLE
Plugin not importing

### ISSUE THREAD

**Issue by ericgl** [pnedev/comparePlus#316]
So I just downloaded this new v1.0 ComparePlus Plugin.
Extracted the files to **C:\Program Files\Notepad++\Plugins\ComparePlugin**.

Using Notepad++ v8.4.4 x64 on Windows 11 x64 en-US.
Settings > Import > Import plugin > Selected the **ComparePlus.dll**. 
Nothing happens, even after closing and restarting Notepad++.

This procedure worked with the previous Compare Plugin v2.0.2.
Am I doing something wrong?

**Comment by ericgl** [comment]
Never mind. Closing the issue.
After fiddling with it a bit, it suddenly appeared in the Plugins list.

**Comment by pnedev** [comment]
@ericgl ,

**ComparePlus** is completely new plugin and should be put in folder **C:\Program Files\Notepad++\Plugins\ComparePlus** if installed manually.
Please read the README (https://github.com/pnedev/comparePlus#readme) for detailed info.
