### ISSUE TITLE
'Operation ignored' when comparing 2 different sections of a file and its clone

### ISSUE THREAD

**Issue by HolterPhylo** [pnedev/comparePlus#325]
Getting this reply when trying to compare 2 different selected sections in a file and its clone using button 'Compare selections'!

![image](https://user-images.githubusercontent.com/3037251/194116690-dcc0ed31-18b1-4143-988d-70c60976ce82.png)

I don't know if I am doing something wrong?  Can a file and its clone be compared when selecting different sections of the file?

Using np++ v8.4.5 64-bit on Windows 10 Pro
Version	21H2
OS build	19044.2075
Experience	Windows Feature Experience Pack 120.2212.4180.0

**Comment by pnedev** [comment]
Hello @HolterPhylo ,

You can do such comparison but not that way. You cannot compare a file (or its selection) to its clone.
Just open the file, select the first selection and copy it to clipboard. Then select the second selection and trigger `Compare to Clipboard` from the plugin menu.

Hope that helps. If you have further questions please re-open the ticket.

BR

**Comment by HolterPhylo** [comment]
Thanks
