### ISSUE TITLE
Author link opens blank webpage

### ISSUE THREAD

**Issue by Tcip** [pnedev/comparePlus#327]
The author link _(Pavel Nedev)_ from the popup window _"Help / About..."_ just opens a blank web page for me. The other two links _("Help and Support", "User Guide")_ below work just fine. Getting the same result with a brand new portable Notepad++ v8.4.6 _(English language)_.

- Windows 10 21H2 (19044.2075)
- Notepad++ v8.4.6, 32-bit, Swedish language
- ComparePlus v1.0.0 (sep 1 2022, 13:11:43)

![ComparePlus_author_link_blank_page](https://user-images.githubusercontent.com/3928913/195372516-4ce618e1-e1a7-40b9-bfa4-80837ac6b188.png)

**Comment by Yaron10** [comment]
@Tcip,

It opens my Email-client. I suppose it depends on your Windows "mailto" settings.

**Comment by pnedev** [comment]
@Tcip ,

As Yaron mentioned it seems that you do not have default program set as an e-mail client. This link is just my e-mail in case someone needs to write me a personal message and is handled by the operating system if it has e-mail client program.

> ... just opens a blank web page for me.

Isn't my e-mail visible in the browser's address box?

Thank you @Yaron10 :+1: 

BR
