### ISSUE TITLE
Blinking: First vs. Last

### ISSUE THREAD

**Issue by Yaron10** [pnedev/comparePlus#328]
Hello Pavel,

Could you please compare a file containing some lines to an empty document?
Activate the empty document.
Press First (line is blinking).
Press Last (line is NOT blinking).

![תמונה](https://user-images.githubusercontent.com/10229320/195607139-e2edbc85-c9b2-4bac-a391-5964f5af1b19.png)

Thank you for looking into it.

BR

**Comment by pnedev** [comment]
Hello Yaron,

I will look into it but I might leave this as a known issue.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for looking into it. I appreciate that.
A known issue is legit. :)

BR

**Comment by pnedev** [comment]
Hello Yaron,

That issue should be gone [here](https://ci.appveyor.com/project/pnedev/compareplus/builds/45174796).
Thanks for the catch!

BR

**Comment by Yaron10** [comment]
Hello Pavel,

👍 
Thank you very much for the fix. I appreciate your hard work.

**OFF-TOPIC.**
Regarding https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12385:
I have encountered this issue numerous times.
But in my workflow it would start with the `Find Incremental Bar` going to a line, and I wasn't sure it was a CP issue.

I'm glad @przemo20 found a simple way to reproduce that major issue.
And thank you again for fixing it.

BR
