### ISSUE TITLE
Crash when compare simple json file

### ISSUE THREAD

**Issue by byzod** [pnedev/comparePlus#331]
[files.zip](https://github.com/pnedev/comparePlus/files/9900729/files.zip)

Compare `it_IT.json` and `fr_FR.json` fails and npp crashed before showing result

But compare `it_IT.json` and `ru_RU.json` succeed?

I'm using a non-released x64 version [here](https://github.com/pnedev/comparePlus/issues/318#issuecomment-1238106665)

```
Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\App\Something\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Home China (64-bit) 
OS Version : 21H2
OS Build : 19044.2130
Current ANSI codepage : 936
Plugins : 
    BetterMultiSelection (1.5)
    ComparePlus (1)
    CSharpRegexTools4Npp (1.1.2)
    EmmetNPP (1.0.2)
    HexEditor (0.9.12)
    JSMinNPP (1.2006)
    mimeTools (2.8)
    nppAutoDetectIndent (2.3)
    NppConverter (4.4)
    NppExport (0.4)
    NppTextViz (0.4.2)
    PythonScript (2)

```

**Comment by Yaron10** [comment]
@byzod,

Could you try the latest version?
https://ci.appveyor.com/project/pnedev/compareplus/builds/45218877/job/1pxka9yde7ullwa2/artifacts

**Comment by byzod** [comment]
> @byzod,
> 
> Could you try the latest version? https://ci.appveyor.com/project/pnedev/compareplus/builds/45218877/job/1pxka9yde7ullwa2/artifacts

Thanks, it fix the problem

**Comment by Yaron10** [comment]
Great.
The thanks and flowers to @pnedev. :)

**Comment by pnedev** [comment]
Hello @byzod , hello @Yaron10 ,

OK, thank you guys :+1: 
Closing the issue now.

BR

**Comment by Yaron10** [comment]
Thank you Pavel. 👍
