### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by cirolosapio** [pnedev/comparePlus#336]
since notepad++ supports dark mode it would be nice if this amazing plugin supports too

actual behaivor:
![image](https://user-images.githubusercontent.com/33943143/204097931-5b047103-b116-4fa4-bfd2-f343764d45ec.png)

**Comment by Yaron10** [comment]
@cirolosapio,

https://community.notepad-plus-plus.org/topic/23434/new-plugin-compareplus-v1-0-0.
https://github.com/pnedev/comparePlus/releases.

**Comment by pnedev** [comment]
Thank you for helping Yaron :)

**Comment by Yaron10** [comment]
My pleasure. :)

**Comment by pokemaster974** [comment]
I dig up this issue but it's sad that comparePlus isn't considered has an update of compare into Notepad++.
I never know that dark mode have been in adapted and live with it since more one year.
Thanks to this issue I install comparePlus !
