### ISSUE TITLE
Add possibility to call via command line

### ISSUE THREAD

**Issue by juxeii** [pnedev/comparePlus#337]
Would it be possible to add the possibility to call comparePlus from the command line?

**Comment by Yaron10** [comment]
https://community.notepad-plus-plus.org/post/81273.
https://github.com/pnedev/comparePlus/releases.

**Comment by Yaron10** [comment]
The flowers to @pnedev. :)

**Comment by pnedev** [comment]
Thank you again Yaron for your ongoing support with user questions like this :+1: 
Very much appreciated :)

**Comment by Yaron10** [comment]
👍
