### ISSUE TITLE
Missing from plugins list

### ISSUE THREAD

**Issue by RichardD2** [pnedev/comparePlus#344]
ComparePlus is no longer listed in the "plugins admin" list, so it cannot be installed on a new computer. Only the old "Compare" plugin is listed.

![image](https://user-images.githubusercontent.com/2158265/211524217-a29808c7-ef8d-42f9-bc9b-54738bcb394e.png)

**Comment by pnedev** [comment]
What Notepad++ version are you using?
In the down-right corner of the PluginsAdmin is written the plugin list version. What is it?
You could also check the `Installed` or `Update` tabs of PluginsAdmin window to make sure ComparePlus is not already installed.

**Comment by RichardD2** [comment]
Notepad++ v8.4.8
Plugin list version 1.5.7

I've tried on multiple machines - mine, which already has ComparePlus installed, and others which don't have it installed. It's not listed on any of them.

I've also opened an issue on the plugin list repository, in case it's their problem:
[Missing pluin - Issue #560](https://github.com/notepad-plus-plus/nppPluginList/issues/560)

**Comment by RichardD2** [comment]
Aha! It's not showing as installed, and the toolbar isn't visible, but it *is* showing in the "updates" list.

![image](https://user-images.githubusercontent.com/2158265/211556215-264875e4-6572-4101-a3c8-8411419a13e8.png)

![image](https://user-images.githubusercontent.com/2158265/211556273-71da125a-15dc-4f81-8003-95bb9b733cc2.png)

Seems a bit odd, but at least I can get it back up and running now.

Thanks for you help.

**Comment by RichardD2** [comment]
Looks like v1 isn't compatible with Notepad++ 4.8.x. I've just updated another server from 4.7.x to 4.8.4, and the ComparePlus toolbar disappeared after the update. Updating the plugin to 1.1 restored it.

**Comment by pnedev** [comment]
> Looks like v1 isn't compatible with Notepad++ 4.8.x.

Yes, plugin version 1.0.0 is not compatible with NPP v8.4.8 due to some internal NPP changes.
