### ISSUE TITLE
[Suggestion] Fully ignore CR/LF

### ISSUE THREAD

**Issue by mdrmdrmdr** [pnedev/comparePlus#349]
Any chance, that **comparePlus**, compares the following two code blocks, one 3 lines and one 1 line, as equal?
They just differ in whitespaces and I cannot find a setting to achieve this.

```
function(a) {
  return "x";
}
```

and

`function(a) { return "x"; }`

**Comment by pnedev** [comment]
Hello,
Unfortunately ComparePlus cannot achieve this as it is working on a line-by-line basis.
BR
