### ISSUE TITLE
Crashes after done comparing

### ISSUE THREAD

**Issue by sovalyeler** [pnedev/comparePlus#353]
Hi. Thanks for this plugin. I've been using old compare plugin for a while. Today, I've discovered Compare-plus, installed it; however, it just crashes after finishing comparing two text files. I'm on NPP v8.5.2
Note: The issue is present on v8.5.1 also.

**Comment by pnedev** [comment]
Hi,

Can you please share a little more details?
How did you install ComparePlus? What is its version? Do you have other plugins installed?
Could you try using PluginsAdmin Notepad++ window (from the Plugins menu) and remove your installed Compare and ComparePlus plugins and then install again ComparePlus via PluginsAdmin? You could also try temporarily remove all other plugins as well.

Is it possible for you to share the files you are comparing (if those are not confidential) or maybe just try comparing other files and tell me if Notepad++ crashes again?

Thanks,
BR

**Comment by pnedev** [comment]
I'll see what I can do but it might be a bug in TextFX2 plugin and I'll need to investigate its code to find the root cause. It is not something I am very enthusiastic about.

**Comment by pnedev** [comment]
I will check the issue when I get to this, thanks.
BR

**Comment by pnedev** [comment]
I use Notepad++'s status bar space in ComparePlus (to display compare info) by intercepting Notepad++ window notifications procedure and it appears that TextFX2 does that as well. This leads to wrong handling and restoration of the original Notepad++ window procedure leading to crashes and/or undefined behavior.

I have made ComparePlus to no longer intercept and change Notepad++ window notifications procedure (as it seems to be a potential inter-plugin vulnerability). This fix will be available in the next plugin release but until then you could use the current dev build: **[win32](https://ci.appveyor.com/api/buildjobs/nuj73295vwu97pp7/artifacts/ComparePlus.dll)**, **[win64](https://ci.appveyor.com/api/buildjobs/vvbqel581pt7ap0y/artifacts/ComparePlus.dll)**

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much for this fix as well. 👍 

May I ask if the old status-bar info-toggling is more complex with the new implementation?
(Just curious; the new behavior is perfectly fine).

Do you think it's better to display `Compare Options` & `Compare Summery` in two separate commands? 

BR

**Comment by pnedev** [comment]
Hello Yaron,

> May I ask if the old status-bar info-toggling is more complex with the new implementation?

Since I stopped intercepting the Notepad++ window procedure I am no longer able to intercept the user click action on the status bar. That's why I implemented the new `Active Compare Options` command. I intend to make a setting that selects what info to display in the status bar - summary of diffs or compare options.

> Do you think it's better to display Compare Options & Compare Summery in two separate commands?

I don't know. Maybe its better to have one command displaying the full info. What do you think?

Thanks.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

> Since I stopped intercepting the Notepad++ window procedure I am no longer able to intercept the user click action...

Thank you for the explanation.

> Update - I have combined both commands info into Active Compare Summary. 

👍 
Great. Thank you for that too.

BR

**Comment by Yaron10** [comment]
Hello again Pavel,

> I intend to make a setting that selects what info to display in the status bar - summary of diffs or compare options.

Are you planning to add that setting in the Settings dialog or in the menu?

In Settings you can have a ComboBox with `None`, `Diffs` and `Options`.
In the menu you can have `Toggle Status Bar Info (Diffs/Options)`. - *And the user would still be able to quickly toggle the info by adding a toolbar button (via CustomizeToolbar)*.

What do you think?

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I already implemented it as a setting. It is better to keep the plugin menu as short as possible and leave there only the commands and the most commonly accessible functions/configs.
Please check the dev binaries **[x86](https://ci.appveyor.com/api/buildjobs/9ww21e2m9ak3aien/artifacts/ComparePlus.dll)** or **[x64](https://ci.appveyor.com/api/buildjobs/i3enii3wsb3a4jad/artifacts/ComparePlus.dll)**.

Thank you,
BR

**Comment by Yaron10** [comment]
Hello Pavel,

My timing wasn't the best. :)

It's beautiful! 👍 
Thank you very much.

If you select `Disabled` and re-Compare, it takes effect only after switching to a non-Compare tab and back.
Is that intentional?

BR

**Comment by pnedev** [comment]
Hello Yaron,

It is not intentional but in order for the status bar to be updated Notepad++ needs to reload it. I'll check if I can force that from CP but more likely I'll leave it this way.
Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> It is not intentional but in order for the status bar to be updated Notepad++ needs to reload it.

I thought about that after posting. :)

> more likely I'll leave it this way.

👍 
Yes, it's not worth the extra work/code.

Thanks again. I appreciate it.

BR
