### ISSUE TITLE
[Request]  Compare "From" - "To"  Column

### ISSUE THREAD

**Issue by Krammig** [pnedev/comparePlus#354]
Many times it is necessary to compare two files, say for example a Bat / Text file that has a long list of instruction. For example a series of regsvr32 /s in one file and regsvr32 /u /s in another file. Just as an example ...

To be able to run a compare on the two files where you could specify the starting "Column" in each of the two files (different in each file) would be in my mind a great addition to this plugin.

**Comment by pnedev** [comment]
Hi,
If you are talking about the ComparePlus plugin it has `Ignore Regex` option in the menu that can do that.
I am not good with regular expressions but I think it won't be hard to come-up with the right one that will suit your needs ("ignore the first N of any character from start of line" or "ignore the first any characters from start of line to the first X character", etc.).
Tell me if that works for you.
BR

**Comment by pnedev** [comment]
Hello again,
As far as I understood from https://cplusplus.com/reference/regex/ECMAScript/ to ignore the first N number of characters (so to start comparing each line from column N) you could use `Ignore Regex...` with this pattern: `^.{N}`
I will close this issue now. If you have further questions feel free to write here continuing this thread or create another issue.
Thanks.
