### ISSUE TITLE
Resuming normal view clears the alpha channel from custom caret line background

### ISSUE THREAD

**Issue by rdipardo** [pnedev/comparePlus#356]
#### Steps to Reproduce

1. Set the caret line background to a *translucent* color, e.g. `0x28FF009C`; for example, by executing this [NppExec](https://github.com/d0vgan/nppexec) script:

        SET SCI_SETELEMENTCOLOUR = 2753
        SET SCI_SETCARETLINELAYER = 2765
        SET SC_ELEMENT_CARET_LINE_BACK = 50
        SET SC_LAYER_UNDER_TEXT = 1
        SCI_SENDMSG $(SCI_SETELEMENTCOLOUR) $(SC_ELEMENT_CARET_LINE_BACK) 0x28FF009C
        SCI_SENDMSG $(SCI_SETCARETLINELAYER) $(SC_LAYER_UNDER_TEXT)

2. Before opening the compare view, the caret line background should be translucent:

![normal_view_before_compare_8 5 3](https://github.com/pnedev/comparePlus/assets/59004801/7fe1e025-a635-4437-870e-a768496c41cd)

3. Open the compare view; close it again.

4. The caret line background is now solid:

![normal_view_after_compare_npp_8 5 3](https://github.com/pnedev/comparePlus/assets/59004801/c1d925e7-e08e-42dc-97f5-6b691570c063)

#### Problem code path

The `setNormalView` function uses a 24-bit BGR color mask that clears the top 8 alpha bits; it also sets the `SC_LAYER_BASE` flag, which will cancel transparency effects in any case:

https://github.com/pnedev/comparePlus/blob/64a9ee43bbda6755a0cdb784e6b1b3decdb0af6f/src/NppHelpers.cpp#L376-L382

This could be seen as a negative interaction with user scripts and other plugins that customize the caret line background. There's a least [one case][1] of a plugin developer thinking that the alpha channel was disappearing because of a bug in his own code.

#### Version
1.1

[1]: https://github.com/BdR76/CSVLint/issues/68

**Comment by pnedev** [comment]
Hi guys,

That is the best I can do : https://github.com/pnedev/comparePlus/commit/a374a82131a53f4c4e6fbc5ad397899d9cfc1091
I'm closing this issue now - please write again here if you think there is still something that can be done better.

Thanks.
BR
