### ISSUE TITLE
Annotations have pink background after compare

### ISSUE THREAD

**Issue by vinsworldcom** [pnedev/comparePlus#362]
From a clean install of the Notepad++ 64-bit 8.5.4 latest version, whenever I do a compare, any subsequent use of annotations just shows a "pink" line.  I think it may have something to do with the styles set and the markers assigned during compare?

1) Open Notepad++ and use File => New to have 2 open files
2) Plugins => ComparePlus => Compare
3) The blank files will "compare" and provide the "Files match .." prompt, just press "OK"
4) Using the NppExec Plugin, set an annotation style and make them visible:

`SCI_SENDMSG SCI_ANNOTATIONSETSTYLE 0 95`
`SCI_SENDMSG SCI_ANNOTATIONSETVISIBLE 2`

5) Using the NppExec plugin, set an annotation:

`SCI_SENDMSG SCI_ANNOTATIONSETTEXT 0 "hello world"`

6) It appears pink:

![image](https://github.com/pnedev/comparePlus/assets/9657169/22e87f27-aa93-42a8-acd0-6829790b3d68)

By contrast, here is steps 4 - 5 *without* having run a compare first:

![image](https://github.com/pnedev/comparePlus/assets/9657169/fc89235c-44b0-439f-ade0-24e127253973)

Debug Info:

Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : C:\Users\mvincent\Downloads\npp\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 21H2
OS Build : 19044.3208
Current ANSI codepage : 1252
Plugins : 
    ComparePlus (1.1)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExec (0.8.5)
    NppExport (0.4)

**Comment by vinsworldcom** [comment]
The issue seems to stem from:

"src/NppHelpers.cpp"
```
206: void setBlanksStyle(int view, int blankColor)
207: {
208: 	if (blankStyle[view] == 0)
209: 		blankStyle[view] = static_cast<int>(CallScintilla(view, SCI_ALLOCATEEXTENDEDSTYLES, 1, 0));
210: 
211: 	CallScintilla(view, SCI_ANNOTATIONSETSTYLEOFFSET,	blankStyle[view], 0);
```

which sets the `SCI_ANNOTATIONSETSTYLEOFFSET` to 256 where in Notepad++, it is normally 0.  After closing compares, it is never reset back to 0.  Manually setting it back to 0, via NppExec for example:

```
SCI_SENDMSG SCI_ANNOTATIONSETSTYLEOFFSET 0
```

 makes the Pink annotations go away.

Cheers.

**Comment by pnedev** [comment]
Hi @vinsworldcom ,

Yes, I am using in ComparePlus Scintilla annotations to mark the blank lines but I never thought that they were used in Notepad++ and that's why I didn't bother to store their config before compare and restore them after.
I'll make the necessary changes.

BR

**Comment by vinsworldcom** [comment]
> but I never thought that they were used in Notepad++

They aren't, but I have a plugin / PythonScript that uses them.  I'm using styles 95-97 so I try to stay high above any used.  I really think all that is needed is to "reset" `SCI_ANNOTATIONSETSTYLEOFFSET` back to `0` when you close compares.

Cheers.

**Comment by pnedev** [comment]
Hello again Vince,

Could you try the last master branch build?
Here are the compiled binaries: **[64-bit](https://ci.appveyor.com/api/buildjobs/mols2ibr09k1iy02/artifacts/ComparePlus.dll)** / **[32-bit](https://ci.appveyor.com/api/buildjobs/0aasmmckynun3bm2/artifacts/ComparePlus.dll)**

Please close this ticket if things are working OK for you now.
Thanks.

**Comment by pnedev** [comment]
Ah, OK, can you please try again with this binary: **[32-bit](https://ci.appveyor.com/api/buildjobs/ppkcy3yqr9mml4f1/artifacts/ComparePlus.dll)** / **[64-bit](https://ci.appveyor.com/api/buildjobs/urc6x0i8e9o764qu/artifacts/ComparePlus.dll)** ?

Thanks again.

**Comment by vinsworldcom** [comment]
@pnedev 
That appears to have done it!

Thank you for the quick turnaround!

Cheers.

**Comment by vinsworldcom** [comment]
I may have spoken too soon, the e6bcb086 commit causes some issues on exiting Notepad++.  It doesn't crash, but I get an hour glass for some time and using ProcExp, I see WerFault running with Notepad++ context:

![image](https://github.com/pnedev/comparePlus/assets/9657169/7166cad0-9f33-4330-8d9e-a2513bad31c0)

This does not happen with the previous commit.

Cheers.

**Comment by vinsworldcom** [comment]
@pnedev 

Thank you for the quick response.  I just tried the new 64-bit from 1d4a0717 and I no longer see the extended Notepad++ close or the Windows fault reporting.  I think that did it!

Thank you for your continued innovation on this essential plugin!

Cheers.
