### ISSUE TITLE
Is it possible to save the compare result?

### ISSUE THREAD

**Issue by byzod** [pnedev/comparePlus#363]
I downloaded a mod for a game, the mod support of it is very primal so I have to merge few mods that mod the same file manually

If the game updated (Steam will force update it) and the modded file was changed, bug and crush are expected

So I have to record what I modded, and change respective lines manually base on the updated file after game updates (if any)
![1](https://github.com/pnedev/comparePlus/assets/848607/94753c3c-832f-4d6a-a12b-bc3fd464a491)

I have to screenshot the compare result because even it displayed changed lines only but when I selected it, all lines including hidden ones are copied

Is there a way to save my compare result with editable info? Similar to github commit log like [this](https://github.com/pnedev/comparePlus/commit/575cb01ed16aaa8eeabd65e64231fa1e04c19d1f)?

I could upload my mod to github and generate such commit log but I'm not sure if it breaks the EULA of the game since it's original files from the game data folder

**Comment by pnedev** [comment]
Hi @byzod,

I don't fully understand your request.

Unfortunately (because of Scintilla implementation) it is not possible to copy to clipboard only the shown lines - the hidden lines in-between are by default also copied. I can make a separate command to the ComparePlus plugin to do that.

On the other hand I will probably implement a "Generate Patch" ComparePlus command as it is certainly useful (and several people in the past have mentioned already that it will be helpful for their use-cases) so will that solve your problem as well?

BR

**Comment by byzod** [comment]
> Hi @byzod,
> 
> I don't fully understand your request.
> 
> Unfortunately (because of Scintilla implementation) it is not possible to copy to clipboard only the shown lines - the hidden lines in-between are by default also copied. I can make a separate command to the ComparePlus plugin to do that.
> 
> On the other hand I will probably implement a "Generate Patch" ComparePlus command as it is certainly useful (and several people in the past have mentioned already that it will be helpful for their use-cases) so will that solve your problem as well?
> 
> BR

I don't quite understand your solution too lol

I mean I want to save the compare result in a format with searchable content

Currently my solution is save both copies of orignal file and modded file, then compare them when I want to check what changed

It works great for my need for now, but I wonder if there could be a better way to implement this feature (sorry but I can't think of a good solution)

What I want is "save the compare result (to a .diff file or something) so you can check the result in that moment, even if the actual file was changed", just like the commit history of github, but without the need to upload (possible) sensitive file

Example, I compare the change of `NppHelpers.h` and save it (to npphelper-23-feb-6.diff or something), months later the file already changed many times, but I can still check what I change in 2023 feb 6 from "compare result", similar to [this](https://github.com/pnedev/comparePlus/commit/224a066120d72cbb9e057176afb7d8ffc1bfec57)

**Comment by pnedev** [comment]
OK, I understand now.
Well it seems that the "Generate Patch" ComparePlus command I mentioned will fit your needs.
Could you please confirm if such patch (diff) file format will solve your problem:

`
src/NppHelpers.h
@@ -492,10 +492,10 @@ inline intptr_t getUnhiddenLine(int view, intptr_t line)
 
 inline intptr_t getPreviousUnhiddenLine(int view, intptr_t line)
 {
-    intptr_t visibleLine = CallScintilla(view, SCI_VISIBLEFROMDOCLINE, line, 0) - 1;
+	intptr_t visibleLine = CallScintilla(view, SCI_VISIBLEFROMDOCLINE, line, 0) - 1;
 
-    if (visibleLine < 0)
-        visibleLine = 0;
+	if (visibleLine < 0)
+		visibleLine = 0;
 
 	return CallScintilla(view, SCI_DOCLINEFROMVISIBLE, visibleLine, 0);
 }
`
?

**Comment by pnedev** [comment]
> Yes, result file like this should work, it can be generated by Git but as I mentioned above, I'm not sure if I can upload game assets to it to generate such thing

What I meant is that at some point I might add such function to ComparePlus - to generate a kind of patch after the comparison for future reference (and probably a functionality to apply the patch on some other computer later).
It appears that will not be soon though as working on ComparePlus is currently not in my priority list.

About the solution you propose - it is something very custom and not a common use-case so I don't think it's implementation is justified, sorry about that.
If you manually store both files (as is your current solution) you can do sort-of "auto compare when open" if you use the "Compare from command line" functionality. It is written how you can do that in the latest plugin ReleaseNotes.

BR

**Comment by pnedev** [comment]
This request should be covered when https://github.com/pnedev/comparePlus/issues/188 is implemented so closing it now as a sort of duplicate.

@byzod ,
Feel free to write here again or open another issue if you have other ideas/requests.

BR
