### ISSUE TITLE
This plug-in should automatically toggle tabs visibility when comparing

### ISSUE THREAD

**Issue by ScienceDiscoverer** [pnedev/comparePlus#364]
The problem is, when you have many tabs opened in main view, and only 1 in side view, the comparison is skewed:

![tabs_issue](https://github.com/pnedev/comparePlus/assets/29157485/a5a1073d-7895-46c4-b3c3-a7f93c69da64)

_Tip:_ you can toggle tabs ON/OFF like this:

```
bool tabs_hidden = SendMessage(npp_data._nppHandle, NPPM_ISTABBARHIDDEN, 0, 0);
SendMessage(npp_data._nppHandle, NPPM_HIDETABBAR, 0, !tabs_hidden);
```

**Comment by Yaron10** [comment]
@ScienceDiscoverer,

The author, @pnedev, has already addressed this issue.
https://ci.appveyor.com/project/pnedev/compareplus/builds/47564611.

**Comment by pnedev** [comment]
Hello,

Thank you Yaron! :)

@ScienceDiscoverer,

ComparePlus plugin should not have that problem as Yaron mentioned.
What plugin version are you using and what Notepad++ version?

BR

**Comment by pnedev** [comment]
Closing this issue as not valid for ComparePlus plugin.
