### ISSUE TITLE
Feature request: Ability to copy unique differences

### ISSUE THREAD

**Issue by vbguyny** [pnedev/comparePlus#366]
I love this plugin, however, I needed to copy the unique differences between two files it doesn't work. When I copy all of the lines it includes all of the lines that are hidden as well.

**Comment by pnedev** [comment]
Hello,

A feature allowing that was implemented recently (it is not officially released yet but will be present in the next ComparePlus release). For detailed info please look at this issue: https://github.com/pnedev/comparePlus/issues/338

In short you can follow the instructions in **[this](https://github.com/pnedev/comparePlus/issues/338#issuecomment-1688066857)** comment to get the current development build of CP (it is best to update Notepad++ to v8.5.6).
Then after a compare you switch to the file which differences you want to copy, open the ComparePlus menu and use one of the new `Bookmark...` commands depending on what type of diffs you want to copy (for example `Bookmark All Diffs in Current View`). This will add a Notepad++ bookmark on every diff line matching that criteria. Next you can use the Notepad++ functionality to copy all bookmarked lines (you will find it under `Search` -> `Bookmark` sub-menu).
If you like you can create custom shortcuts to both these commands for easier and faster access.

Write back if you need more info.
BR
