### ISSUE TITLE
Algorithm? Standalone?

### ISSUE THREAD

**Issue by philippbc** [pnedev/comparePlus#367]
I’m looking for a tool to compare a large number of code files. I’ve looked far and wide (WinMerge, Beyond Compare, …), but this plugin actually gets the best results (by a distance). Could you shed some light on the algorithm you use and any possibility of calling the comparison programmatically and saving a diff/patch file (e.g., command line, from Python)?

**Comment by pnedev** [comment]
Hello,

I didn't implement the algorithm myself - I just enhanced the long-time existing original Compare plugin.
As far as I understand (from the comments in the code - please see `diff.h` file at its beginning where the license info is) the comparison algorithm used is Myers' and it is claimed this is the same algorithm used by GNU diff.

You can invoke ComparePlus plugin comparison directly from command line with this command:
`notepad++ -pluginMessage=compare new_file.txt old_file.txt`
Currently it is not possible to generate patch file.

BR
