### ISSUE TITLE
Notepad++ now disappears when comparing relatively small simple files

### ISSUE THREAD

**Issue by mouse-slammer** [pnedev/comparePlus#370]
I compared some quite large files and I believe this caused Notepad++ to crash.
Now when I compare a pair of small files which would normally not cause a problem then Notepad++ seems to crash. Is there some persistent state which has got corrupted? 
It does the compare and the compared files show up with the colour highlighting for a second and then it crashes.
ComparePlus 1.1.0 Nov 2 2022 16:36:24 

Notepad++ v8.5.4   (64-bit)
NppTextFX (1.4.1)
(snipped various settings and version numbers no longer relevant)
I updated to Notepad++ v8.5.7   (64-bit)
Build time : Sep  6 2023 - 23:13:49
Same behaviour

**Comment by pnedev** [comment]
No, there is no persistent ComparePlus state that might be corrupted and lead to such behavior.

Could you please try temporarily removing all other plugins (except ComparePlus) and try again?
If the crash does not appear in that setup you could try removing only NppTextFX plugin and retry the test.
Tell me if that fixes the issue and we'll discuss further, thanks.

BR

**Comment by mouse-slammer** [comment]
Thanks for the prompt reply. 
I can no longer reproduce the issue after fiddling with various TextFX settings. I don't know exactly what made it go away but I'm now confident it was a TextFX issue rather then anything ComparePlus. Thanks for ComparePlus!

**Comment by pnedev** [comment]
There is an existing compatibility issue with TextFX related to the usage of the Notepad++ status bar by the two plugins.
I have made a fix in ComparePlus but the new release of the plugin is not ready yet. Everything should be OK in the next version.
Thanks.
