### ISSUE TITLE
comparePlus 1.1.0 crashes NPP

### ISSUE THREAD

**Issue by G234i** [pnedev/comparePlus#371]
ComparePlus crashes NPP v8.5.7(x64) on Win 11.

It appears to successfully compare the files then freezes up and crashes.

Replacing the .dll with the latest build (Build 752) from https://ci.appveyor.com/project/pnedev/compareplus seems to fix the issue

> Notepad++ v8.5.7   (64-bit)
Build time : Sep  6 2023 - 23:13:49
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Enterprise (64-bit)
OS Version : 22H2
OS Build : 22621.2134
Current ANSI codepage : 1251
Plugins : 
    ComparePlus (1.1)
    JSMinNPP (1.2205)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (1.40)
    NppTextFX2.1.4.1.x64 (1.4.1)
    XMLTools (3.1.1.13)

**Comment by rdipardo** [comment]
NppTextFX2 is not compatible ComparePlus (v1.1.0 or older): notepad-plus-plus/notepad-plus-plus#13956

**Comment by pnedev** [comment]
As @rdipardo said currently NppTextFX2 and ComparePlus have interoperability issue.
The new ComparePlus release will have that fixed but meanwhile either use only one of them or try playing with NppTextFX2 settings to disable its Notepad++ status bar usage if possible.

**Comment by adamzovits** [comment]
The latest development build had its artifact deleted according to the AppVeyor Artifacts retention policy. How could I get the working build or when is a release planned?

**Comment by pnedev** [comment]
Here is a link to a new development build that you can use:
**[32-bit](https://ci.appveyor.com/api/buildjobs/0asbkf55a6nqf112/artifacts/ComparePlus.dll)** / **[64-bit](https://ci.appveyor.com/api/buildjobs/fte8jddwcmmcxv7g/artifacts/ComparePlus.dll)**

I will try to prepare a new release during the holidays, there are a few more things I'd like to polish before that but I don't promise anything, sorry.

BR
