### ISSUE TITLE
Ability to Copy-Paste only new or changed strings in Show Only Diffs (Hide Matches) mode

### ISSUE THREAD

**Issue by ss7877** [pnedev/comparePlus#381]
Hi, Pavel.
Thank you very much for ComparePlus. It's the most useful plugin of Notepad++ for me.

I would like to suggest adding one very useful, in my opinion, feature to it.
Ability to Copy-Paste only new or changed strings in Show Only Diffs (Hide Matches) mode.

Now when I select several strings in this mode and make Copy-Paste to a new document, I get all the lines that are between the first and the last lines - new + changed + identical lines.

If you introduce the ability to copy only new and modified lines in this mode, it will radically reduce the time it takes to transfer such lines to another document.

For example, I am currently transferring new lines from patch 6 for Baldur's Gate 3 to my localization fixes, and I have to transfer each of the 2,400 new lines manually. With the suggested option, I would be able to transfer text in blocks, which would save many hours of manual work.

Best regards,
Alexander

**Comment by pnedev** [comment]
Hello Alexander,

Such feature is indeed quite useful and luckily it is already implemented but the new release is not out there yet.
If you like you can get the development version of the plugin and install it manually as I describe in **[this](https://community.notepad-plus-plus.org/topic/25461/comparing-and-editing-files/6?_=1708247315502)** Notepad forum thread.

You could also look at https://github.com/pnedev/comparePlus/issues/366 and https://github.com/pnedev/comparePlus/issues/338 which are the previous requests for the same feature but the links to the development builds there will already be expired. I put them here more as a reference.

Write back here if you need further assistance or you have questions.

BR

**Comment by ss7877** [comment]
Thank you very much.
You'd saved my Sunday :)
