### ISSUE TITLE
Navigation bar not showing

### ISSUE THREAD

**Issue by byzod** [pnedev/comparePlus#383]
![An1](https://github.com/pnedev/comparePlus/assets/848607/280f88f8-7179-40f4-b2f4-d51756ee56ac)

![2](https://github.com/pnedev/comparePlus/assets/848607/5c235d0f-ca68-4119-b364-721810793e9f)

```
Notepad++ v8.6.4   (64-bit)
Build time : Feb 20 2024 - 00:12:59
Path : C:\App\Something\Notepad++\notepad++.exe
Command Line : "K:\Down\R\1.txt"
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Home China (64-bit)
OS Version : 21H2
OS Build : 19044.3086
Current ANSI codepage : 936
Plugins : 
    BetterMultiSelection (1.5)
    ComparePlus (1.2)
    CSharpRegexTools4Npp (1.1.2)
    EmmetNPP (1.0.2)
    HexEditor (0.9.12)
    JSMinNPP (1.2006)
    mimeTools (3.1)
    nppAutoDetectIndent (2.3)
    NppConverter (4.6)
    NppExport (0.4)
    NppTextViz (0.4.2)
    PythonScript (2)

```

**Comment by pnedev** [comment]
You need to enable Navigation Bar from the plugin menu -> `Plugins`->`ComparePlus`->`Navigation Bar` (should have 'tick' sign near it).
The other way is to use the NavBar plugin button on Notepad++ toolbar -> in your screenshot it is exactly on the left next to the green (Re) icon.
Write again here if you have further questions.

**Comment by byzod** [comment]
> You need to enable Navigation Bar from the plugin menu -> `Plugins`->`ComparePlus`->`Navigation Bar` (should have 'tick' sign near it). The other way is to use the NavBar plugin button on Notepad++ toolbar -> in your screenshot it is exactly on the left next to the green (Re) icon. Write again here if you have further questions.

1. I'm not that stupid
![1](https://github.com/pnedev/comparePlus/assets/848607/baf0ddb0-6709-4792-a4d0-280d3e2ad972)

2. I post the gif for a reason, which showing me click it and nothing happens, did you notice the yellow blink circle?

**Comment by pnedev** [comment]
> I post the gif for a reason...

It appears I am stupid enough to not notice this is a gif and not playing it :)
I looked it like a still picture and noticed the NavBar wasn't enabled.

OK, next thing that comes to mind is that the NavBar docking panel got un-docked and got hidden somewhere.
Could you find your Notepad++ `config.xml` (looking at the info you provided it should be where notepad++.exe is) open it and find the DockingManager section:
`<GUIConfig name="DockingManager" leftWidth="200" rightWidth="343" topHeight="200" bottomHeight="200">` for example.
Under that section manually delete all entries (lines) that are targeted for ComparePlus:
`<PluginDlg pluginName="ComparePlus.dll" ...`

Save it and then restart Notepad++ and try enabling NavBar again.
Tell me if that solves the issue.

**Comment by byzod** [comment]
It comes back, thanks 😄

**Comment by byzod** [comment]
hi pnedev the navigation bar disappeared again, try to change the `isVisible="no"` thing in the config.xml to `="yes"` but not working. Only deleting the whole line can make it appear

But when I restart notepad++, it disappeared again

The config says `no` even if I checked the menu option
![1](https://github.com/pnedev/comparePlus/assets/848607/167c55cc-f80c-427f-a10c-96c0725ecf25)

**Comment by pnedev** [comment]
Hi @byzod ,
Unfortunately I cannot do anything about that - the docking functionality is solely done by Notepad++ - the plugins play no part in it.
Are you sure you are not double-clicking on the docked pane somehow? I don't have other guesses.
Maybe there is something not OK in portable Notepad++ regarding the docking feature, IDK. You are using the portable Notepad++, right?
Do you have other plugins with docked panes? If yes, are those having their docked panes displayed properly?

**Comment by byzod** [comment]
> Are you sure you are not double-clicking on the docked pane somehow? 

Sadly I didn't found the way to reproduce it consistently :(

Double click it just toggle between dock/window mode

> You are using the portable Notepad++, right?

Yes

> Do you have other plugins with docked panes? If yes, are those having their docked panes displayed properly?

Check the plugin list in OP, I don't use any dock panel except some built-in one, but they might have some, idk

**Comment by pnedev** [comment]
> Check the plugin list in OP, I don't use any dock panel except some built-in one, but some plug-in might have some, idk

I haven't used all of those plugins, maybe the HexEditor uses docking panels, IDK for sure.

Well, I really don't know what more I can do - it is a Notepad++ feature. From ComparePlus side I just register the docking window and that's it. I have never observed such problems nor I have heard of someone having issues with that. It might be due to the portable version of Notepad++ or some other plugin interference (for me, the first guess is more likely).
Some time later I might try using ComparePlus with portable Notepad++ on my side but it seems I cannot help you any further, sorry.

**Comment by byzod** [comment]
Hi I finally found how to reproduce this bug

It's a little bit complicated and might contains many useless steps but I didn't found a simplier way to reproduce it

1. Set npp to remember last opened files (my config.xml see attachment, edit out some personal info)
2. Download and complie [massren](https://github.com/laurent22/massren/releases/tag/v1.5.6)
3. Set editor of massren to npp and disable header. Example command:
    ```
    massren --config editor "C:\App\something\Notepad++\notepad++.exe"
    massren --config include_header 0
    ```
5. Create a shortcut of `massren.exe` and rename the shortcut to `massren`, move it to SendTo folder (can be found by run command `shell:sendto`, path be like `C:\Users\[username]\AppData\Roaming\Microsoft\Windows\SendTo`)
6. Get 2 files as target, select them and open. (`1.txt`, `2.txt` in this case)
7. Compare it with Compareplus, drag the navigator out (**note**: the bug can't be reproduced when it's docked, but still bugged with some situation I didn't found yet)
8. Close npp
9. Select `1.txt` and `2.txt`, right click and select `send to > massren`
10. Close massren window and npp without doing anything
11. Open npp, you should see 3 files remembered and opened automatically: `1.txt`, `2.txt` and a auto generated massren file
12. Select the massren file, close it (**note**: I don't know what this step did but it's absolutely required to reproduce it)
13. Now you get only 2 files left (`1.txt` and `2.txt`), compare them
14. Navigator disappeared

demo:
![An2](https://github.com/pnedev/comparePlus/assets/848607/cf5c9223-7fda-4275-957f-8c95fd859049)



my config file:
[config.zip](https://github.com/pnedev/comparePlus/files/15076619/config.zip)

**Comment by pnedev** [comment]
Hi @byzod ,

That's quite a scenario indeed :))

Thank you for the detailed steps and for the effort to come-up with a way to reproduce this issue but it doesn't seem related to ComparePlus itself but more with Notepad++ and the way it is inter-working with massren and its session save-restore functionality. As I said before Notepad++ is dealing with docked/undocked plugin panels (that's its own internal functionality). That's why I find no reason (and will not invest time) to debug the root cause, sorry about that.
If you are curious and have the time you could try following exactly the same steps but with another plugin that uses the docking panels (there are plenty of them, just make sure the docked panel is activated when certain plugin function is used and not by default when Notepad++ is started). If you try that I would be interested to know the result so I'll appreciate if you write it again here for completeness.

Best of luck!

**Comment by xomx** [comment]
Hello @pnedev 
This is most probably the https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14478
The docking/undocking N++ code is flawed. I tried a quick patch but failed - limited spare time as always :-(
