### ISSUE TITLE
How to view .diff single file as comparison in split view? 

### ISSUE THREAD

**Issue by hardiklakhalani** [pnedev/comparePlus#384]
I've a following `xyz.diff` single file which have the changes stored. How to view this using ComparePlus Split View?

Please note that there's no other files. just this. no repo as well. I can see ComparePlus menu does have git related options but none of them seems to work here.
If anyone know any offline/online GUI tool then please suggest me that (only in case ComparePlus won't work with `.diff`)
![image](https://github.com/pnedev/comparePlus/assets/82162165/44a35050-44cd-4c4e-aeae-7d762e3d5802)

**Comment by pnedev** [comment]
This is currently not possible with ComparePlus.
It can compare files but it is not meant to visualize diff files.
