### ISSUE TITLE
After exiting compare, current selected line Colors/Linter is set to black instead of light grey.

### ISSUE THREAD

**Issue by DrewGei** [pnedev/comparePlus#386]
After exiting from compare (including using clear all compares), the selected line linter/highlight is incorrectly set to black instead of light grey. I have to close and re-open Notepad++ to correct.
![image](https://github.com/pnedev/comparePlus/assets/52167794/41c34fea-d8d1-4669-be9e-19ec2dacef16)

**Comment by pnedev** [comment]
What is your Notepad++ version and your Compare plugin version?
Could you please post here the Notepad++ debug info (from Notepad++'s menu -> `?` -> `Debug Info...`) it contains all the info I currently need. Thanks

**Comment by pnedev** [comment]
@DrewGei ,
Could you answer my questions in the previous post please?

**Comment by MK-43** [comment]
same issue!

**Comment by pnedev** [comment]
Closing this issue now as it seems Notepad++ related and it can be resolved as written here:
https://github.com/pnedev/comparePlus/issues/390#issuecomment-2154057201
