### ISSUE TITLE
Show Only Diffs (Hide Matches) doesn't work

### ISSUE THREAD

**Issue by GeneGeneGitHub** [pnedev/comparePlus#389]
After doing a Compare (which does result in many diffs), clicking that button on the toolbar does nothing.

Thanks

**Comment by pnedev** [comment]
Could you print your Notepad++ Debug info (from its menu `?`->`Debug Info...`) here?
Could you try to use `Hide Matches` from the ComparePlus menu (not using the toolbar) and tell me if the result is different?
Are there any matches in your compare (I suppose there are but I had to ask just to be sure they were visible)?

**Comment by pnedev** [comment]
Closing that ticket now as irrelevant (no details given so far).
