### ISSUE TITLE
Perfect match text with black highlights 

### ISSUE THREAD

**Issue by dolphre** [pnedev/comparePlus#390]
When I get a perfect match using ComparePlus (ver. 1.2.0), the entire text is hidden with black highlights. All ComparePlus settings are default, including color settings. "Clear Active Compare" also does not change anything.

![black match](https://github.com/pnedev/comparePlus/assets/171861219/512b14a5-b8fd-48d8-b4d9-3da828fcdcbc)

I also tried to reinstall ComprePlus, but it failed to uninstall. The installation seems to have been processed, but it remains on Notepad++ even after restarting it. So, I can't even reinstall it.

How can I fix the issue?

**Comment by pnedev** [comment]
Could you please post here the Notepad++ debug info (from Notepad++'s menu -> `?` -> `Debug Info...`)? It contains some info that might help. Thanks

**Comment by dolphre** [comment]
@pnedev 
Thank you for your reply. 
I reinstalled Notepad++, and it fixed the issue—at least for now. I'll reach out if I have issues again.
