### ISSUE TITLE
Copy/past hot keys

### ISSUE THREAD

**Issue by ropblHa** [pnedev/comparePlus#393]
How about adding the ability to copy diff lines/sections from left to right and right to left? I often use comparators for editing files - there is some basic version of the file and a new one, and I edit them directly in npp periodically updating the comparison results - and it would be great to have the ability to copy changes between the compared files using hotkeys.

**Comment by pnedev** [comment]
@ropblHa ,
I suppose you have closed the ticket because you have seen this reply in a similar request:
https://github.com/pnedev/comparePlus/issues/391#issuecomment-2168278443 .
Anyway, such feature is already implemented and working OK, it is not obvious and not documented well enough though.
