### ISSUE TITLE
Comparing 2 xml files from printer settings kinda fails

### ISSUE THREAD

**Issue by Serat00l951** [pnedev/comparePlus#396]
[Desktop.zip](https://github.com/user-attachments/files/16443905/Desktop.zip)
![image](https://github.com/user-attachments/assets/8a79b80d-66f5-41e7-859b-9c9236179b26)

Hello. I used powershell commandlet Get-PrintConfiguration to get printer configuration from windows server. There are 2 configuration xml files, both are from the same printer, the difference is the value of one of the parameters in xml. However both files include huge amount of some raw data at the start of the files which a bit different. Your plugin didnt highlight this difference. Can you please fix it? Thank you.

**Comment by pnedev** [comment]
Hello @Serat00l951 ,

The marked with red square sections of the files are actually marked as different by the plugin. The dark orange is the differing part of the lines. Am I missing something?
You can also look at the letters that actually differ (right now you are seeing the differing "words" - not really meaningful in that part of the files). To do so, enable the "Detect Character Diffs" option in the ComparePlus plugin menu and re-compare.

Please describe further what is not working as expected, thank you.

**Comment by Serat00l951** [comment]
> The marked with red square sections of the files are actually marked as different by the plugin. The dark orange is the differing part of the lines.

Yes you are right.  I kinda missed that 😂

I expected that your script would select only the different letters which I marked red. I didnt realize that there was a big whole string in each file and the script selected this big string instead of what I was thinking. So yea its done the job properly, I just didnt consider the length of the string😅

Anyway thanks for pointing to my mistake. I do believe it can be closed.

**Comment by pnedev** [comment]
@Serat00l951 ,
No problem, thanks.

**Comment by krystian3w** [comment]
Version 1.1 of Compare Plus highlights single characters, while the newer one seems to have stopped doing so even in the dev branch.

![Image](https://github.com/user-attachments/assets/14f97a9a-69ca-4002-a1b3-22b854939821)

It's hard for me to determine whether version 1.2 and dev are broken or if it's a bug on Notepad++ or Windows 7 side (insufficient automatic tests on Notepad++ side when publishing newer releases in the last year).

**Comment by pnedev** [comment]
@krystian3w ,

Look in the ComparePlus plugin menu (from the Notepad++'s `Plugins` menu) and search for the character diffs compare option. I suppose it is disabled in your case. If you find it try enabling it - that should configure the plugin to highlight only the characters that differ between the similar lines.

**Comment by krystian3w** [comment]
I have already tried selecting it several times and even clicking save in the advanced settings.

Unfortunately, I can not replace my machine with one compatible with Windows 11 or bypass the locks to use Windows 11 on a processor from the turn of 2011-2012 that is too old.

so it must be some bug on the level of Windows 7 and several versions of Notepad++ (I have to downgrade the plugin, as long as it works with subsequent versions of Notepad++)

**Comment by krystian3w** [comment]
It seems that the dlls associated with the dev2 branch do not allow me to highlight letters (perhaps something is stuck again despite selecting and deselecting “hide all spaces”). Perhaps that's where “Detect Character Diffs” gets lost.

https://github.com/pnedev/comparePlus/commit/3331f5d6c5feec5b5c67e4faa087bfedf599e13c

**Comment by pnedev** [comment]
Hello @krystian3w ,

Please do not use 'dev' branches builds on your own as those branches are not official yet and are current development stages (not completed and fully functional yet). I use those primarily to sync my development between different computers.

BR

**Comment by krystian3w** [comment]
I only use dll files, I don't have any forked Your code on any platform (even localhost).

You overestimate my dll compilation skills.

**Comment by pnedev** [comment]
Again, .dll files automatically build from `dev` branches are NOT OK to be used unless I confirm them to be as those may not be fully functional.
