### ISSUE TITLE
Add option Copy Diff only

### ISSUE THREAD

**Issue by PokemonUnite129** [pnedev/comparePlus#399]
Is possible to do that ?
Example:
File A 
A
B             
F           
C
D
-
File B
A
C
D
-
Compare A and B. After that Ctrl+A copy Diff part only

Then Paste diff part to File C we will get
F
D
-

**Comment by pnedev** [comment]
@PokemonUnite129 ,
To copy only the diff part (particular diff I mean that is not separated from other diff sections) click on the margin diff symbol ('+' sign in your example case). This will automatically mark all lines in that diff section. Than just copy them with CTRL-C and paste them where you want.
If you want to copy all diff sections you'll need to use one of the `Bookmark...` options from plugin's menu and then use Notepad++'s function to copy all bookmarked lines ( you will find it in `Search` -> `Bookmark` menu).
